### ISSUE TITLE
Split out CSSSyntaxGenerator value type handlers

### ISSUE THREAD

**Issue by tpict** [papandreou/css-generators#37]
I'm working on a project with CSS input that only accepts a subset of possibilities for composed values with members that can be placed in any order, i.e. `<line-width> || <line-style> || <color>` must be given _in that order_. This library seems like it would be a great fit for fuzzing my project, but to constrain the output to my parameters I need to copy-paste all of `CssSyntaxGenerator._generate` with the relevant changes.

Would you be opposed to having `_generate` delegate to a separate method for each value type (and each multiplier, combinator type) so that the output can be more easily customized? Thanks!

**Comment by papandreou** [comment]
Sounds like that would be a great change, `CssSyntaxGenerator._generate` is getting pretty unwieldy 😅 

Go for it :rocket:
